org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

minecraft_version=1.21.1
neo_version=21.1.248

mod_id=fwen
mod_name=The FWEN Cult
mod_version=0.1.0
mod_group_id=com.thememecult.fwen
mod_license=All Rights Reserved
mod_authors=basbo
mod_description=Content for the FWEN Cult modpack.
